### ISSUE TITLE
Repo not updated, latest build on dockerhub not working

### ISSUE THREAD

**Issue by lengers** [liyali/moodle-docker#1]
Please update your repository when you update the image on dockerhub. Your latest build there fails to start properly and, lacking your previous Dockerfile, I cannot get up my setup again.

**Comment by 42ae** [comment]
@lengers can you please describe the issue, the `Dockerfile` has not been updated recently so I am surprised to hear it's failing on your end.

**Comment by 42ae** [comment]
Closing this issue since there is no further clarification from @lengers
